[package]
name = "Structure"
version = "0.1"
lean_version = "leanprover/lean4:nightly"

[dependencies]
mathlib4_experiments = {git = "https://github.com/SReichelt/mathlib4_experiments", rev = "9d4bd3334f2c71ccb188f2bccc89062f65eb1ab6"}
