[package]
name = "Structure"
version = "0.1"
lean_version = "leanprover/lean4:nightly-2021-05-30"

[dependencies]
mathlib4_experiments = {git = "https://github.com/SReichelt/mathlib4_experiments", rev = "edf58e8ae32b1112325819a3a3e61386a49021d6"}
