[package]
name = "Structure"
version = "0.1"
lean_version = "leanprover/lean4:nightly-2021-04-24"

[dependencies]
mathlib4_experiments = {git = "https://github.com/kbuzzard/mathlib4_experiments", rev = "7c38eb9741a47ef2997661e2cd08e974a8126e05"}
